### ISSUE TITLE
Support wider array @param syntax

### ISSUE THREAD

**Issue by juliangut** [thecodingmachine/phpstan-strict-rules#24]
PHPStan supports `@param` array syntax such as

```
interface MyClass
{
    /**
     * @param array<string, int> $attributes
     */
    public function __construct(array $attributes = []);
}
```

But `\TheCodingMachine\PHPStan\Rules\TypeHints\AbstractMissingTypeHintRule` returns error when analyzing the docblock

> In method "\MyClass::__construct", for parameter $attributes, invalid docblock @param encountered. "\MyClass\array<string," is not a valid Fqsen.

We end up having to document as `@param int[]` or `@param mixed[]`

**Comment by moufmouf** [comment]
Interesting, I was under the impression that the "array<string, int>" was not supported by PHPStan. I'll give it another look!

AbstractMissingTypeHintRule is using "better-reflection" under the hood, that itself uses "phpdocumentor/type-resolver". I'll keep this issue open until I have some time to see if I can use the same API that PHPStan uses internally.

**Comment by moufmouf** [comment]
Excellent idea!

That was a hell of a refactoring, but I'm almost done: https://github.com/thecodingmachine/phpstan-strict-rules/pull/27
