### ISSUE TITLE
Exception improvements

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/phpstan-strict-rules#33]
When catching `Exception`, `Throwable` or `RuntimeException`, we should ensure that the exception is always rethrown (or wrapped into another exception that is thrown).

**Comment by moufmouf** [comment]
+ need to add the context in the error message.

**Comment by moufmouf** [comment]
and need to update the neon file.

**Comment by odan** [comment]
Rethrowing exceptions is a rare use case for me, because my middleware has to catch and handle them anyway. By the way: I've heard that rethrowing exceptions is considered an anti-pattern (catching, logging, rethrowing).

How can I disable this rule?

**Comment by moufmouf** [comment]
Indeed, if you are developing a middleware, this specific rule does not apply.
I'm planning to add "parameters" to enable or disable specific rules but I haven't done that yet.

In the meantime, you can ignore the error message with a regular expression: https://github.com/phpstan/phpstan#ignore-error-messages-with-regular-expressions

**Comment by juliangut** [comment]
@moufmouf ability to disable certain rules in a way such as PHPMD and other does would be really appreciated as well. I might want to disable a rule for a specific use case in a class (knowing what I'm doing) but leave it on for the rest of the code base

If you find this appealing an issue can be created to discuss what and how

**Comment by moufmouf** [comment]
@juliangut I would absolutely love to have the possibility to disable a rule for a specific use case (a specific method or class) but I believe this ability should be part of PHPStan (and not the phpstan-strict-rules extension). Maybe open an issue to PHPStan?

**Comment by juliangut** [comment]
You're right!
