### ISSUE TITLE
PhpStan 0.11 compatibility

### ISSUE THREAD

**Issue by andreasschroth** [thecodingmachine/phpstan-strict-rules#46]
First of all, thanks for the great work here and the strict rules! 👍 

Currently there is no version compatible with PhpStan 0.11 tagged.

Would be awesome if that would be possible.

**Comment by moufmouf** [comment]
Done, thanks to @nunomaduro #45 .

**Comment by andreasschroth** [comment]
Awesome, thanks for your fast reaction and keep up the good work.
