### ISSUE TITLE
php8 - catch block without var - internal error triggered #4385

### ISSUE THREAD

**Issue by mitalcoi** [thecodingmachine/phpstan-strict-rules#57]
Code example:

 try {
        } catch (NumberReleaseFailedException){ //missed $error var - php 8 allow it
        }

Error: 

  Internal error: PhpParser\NodeVisitorAbstract@anonymous(): Argument #1 ($catchedVariableName) must be of type string, null given, called in                                
    vendor/thecodingmachine/phpstan-strict-rules/src/Rules/Exceptions/ThrowMustBundlePreviousExceptionRule.php on line 34

**Comment by dongm2ez** [comment]
Proposal  link: https://wiki.php.net/rfc/non-capturing_catches
