### ISSUE TITLE
Typehting inspiration

### ISSUE THREAD

**Issue by TomasVotruba** [thecodingmachine/phpstan-strict-rules#7]
I see there are few typehint rules. You maybe plan to add more in time. I already use a tool that takes care of these.

To prevent any more duplicated work, you might use sniffs from [slevomat/coding-standard](https://github.com/slevomat/coding-standard/tree/master/SlevomatCodingStandard/Sniffs/TypeHints), that do pretty much the same.

If you still want to have that duplicated locally in this repository for any personal reason, you can inspire a lot from @slevomat guys.

**Comment by moufmouf** [comment]
Thanks for the tip. I'll definitely have a look at that. I'm leaving the issue open until I do!

**Comment by TomasVotruba** [comment]
Even better solution that combines AST, static analaysis and instant upgrades:
https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#typedeclaration
